ads/urls.py
from django.urls import path, reverse_lazy
from . import views
# from django.views.generic import TemplateView

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name = 'all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name = 'ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name = 'ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name = 'ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name = 'ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url = reverse_lazy( 'ads:all' )), name = 'ad_comment_delete'),
    path('ad/<int:pk>/favorite'  , views.AddFavoriteView.as_view(),           name = 'ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(),        name = 'ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

chat/urls.py
import os
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))




app_name = 'chat'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('syntax', TemplateView.as_view(template_name='chat/syntax.html'),
        name='syntax'),
    path('jsonfun', views.jsonfun, name='jsonfun'),

    path('talk', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]

emi_web/urls.py
#from django.contrib import admin
#from django.urls import path ,include
#
#urlpatterns = [
#    path('admin/', admin.site.urls),
#    path('polls/', include ("polls.urls")),
#    url(r'^site/(?P<path>.*)$', serve,
#        {'document_root': SITE_ROOT, 'show_indexes': True},
#        name='site_path'
#    ]
####
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('users/', include('users.urls')),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
        'show_indexes'  : True}, name='site_path'),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path("hello/", include("hello.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),                   #
    path('authz/', include('authz.urls')),
    path("cats/", include("cats.urls")),
    path("ads/",include("ads.urls")),
    path("chat/",include("chat.urls")),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login,extra_context={
                           "key":github_settings.SOCIAL_AUTH_GITHUB_KEY}))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

chat/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Message(models.Model) :
    text       = models.TextField();
    owner      = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete =models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now     = True)

chat/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.http import JsonResponse, HttpResponse

from chat.models import Message

from datetime import datetime, timedelta
import time

# from django.contrib.auth.models import User

class HomeView(View) :
    def get(self, request):
        return render(request, 'chat/main.html')

def jsonfun(request):
    time.sleep(2)
    stuff = {
        'first': 'first thing',
        'second': 'second thing',
    }
    return JsonResponse(stuff)

class TalkMain(LoginRequiredMixin, View) :
    def get(self, request):
        return render(request, 'chat/talk.html')

    def post(self, request) :
        message = Message(text=request.POST['message'], owner=request.user)
        message.save()
        return redirect(reverse('chat:talk'))

class TalkMessages(LoginRequiredMixin, View) :
    def get(self, request):
        messages = Message.objects.all().order_by('-created_at')[:20]
        results = []
        for message in messages:
            #print(type(message.owner))
            result = [message.text, naturaltime(message.created_at),str(message.owner)]
            results.append(result)
        return JsonResponse(results, safe=False)

chat/templates/chat/main.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<p>Howdy - Lets get some JSON</p>
<p id="back">This text will be replaced in 2 seconds</p>
<p>
<a href="{% url 'chat:syntax' %}"  target = "_new">JSON and JavaScript</a> |
<a href="{% url 'chat:jsonfun' %}" target = "_blank">JSON Endpoint</a>  |
<a href="{% url 'chat:talk' %}"    target = "_blank">Lets Chat</a>
</p>
<br/>
<a href="/">Go to index</a>
<script type="text/javascript">
$(document).ready( 
function () { $.getJSON('{% url 'chat:jsonfun' %}', 
function(data) { $("#back").html(data.first); console.log(data);} ) } ) ;
</script>
{% endblock %}
</body>

chat/templates/chat/syntax.html
<html><head/><body>
<script type="text/javascript">
who = {
    "name": "Emi",
    "age": 46, 
    "college": true,
    "offices" : [ "3350DMC", "3437NQ" ],
    "skills" : { "fortran": 0, "C": 0, 
        "C++": 0, "python" : 7 }
};
console.log(who);
</script>
<p>Check out the console.log to see the cool object</p>
<pre>
who = {
    "name": "Emi",
    "age": 29, 
    "college": true,
    "offices" : [ "3350DMC", "3437NQ" ],
    "skills" : { "fortran": 0, "C": 0, 
        "C++": 0, "python" : 7 }
};
</pre>
</body>

chat/templates/chat/talk.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<h1>Chat</h1>
<form method="post">
{% csrf_token %}
<input type="text" name="message" size="60"/>
<input type="submit" value="Chat"/> 
<input type="submit" name="reset" value="Reset"/> 
<a href="{% url 'chat:main' %}" target="_blank">Cancel</a>
</p>
</form>

<div id="chatcontent">
<img src="{% url 'chat:static' 'spinner.gif' %}" alt="Loading..."/>
</div>

<script type="text/javascript">
function updateMsg() {
    console.log('Requesting JSON'); 
    $.getJSON('{% url 'chat:messages' %}', function(rowz){
        console.log('JSON', rowz);
        $('#chatcontent').empty();
        for (var i = 0; i < rowz.length; i++) {
          arow = rowz[i];
          $('#chatcontent').append('<p>['+arow[2] +
              ']&nbsp;&nbsp;[' +arow[1] + ']&nbsp<span align="left">' + arow[0]+"</span></p>\n");
        }
        setTimeout('updateMsg()', 4000);
    });
}

// Make sure JSON requests are not cached
$(document).ready(function() {
    $.ajaxSetup({ cache: false });
    setTimeout('updateMsg()', 2000);
});
</script>
{% endblock %}